#!/bin/bash

# Wait for the database to become available before proceeding into application.
while ! curl db:3306 >/dev/null 2>&1 < /dev/null; do
  echo "Waiting for database..."
  sleep 1
done

# Migrate the database
python /var/www/whatsup/manage.py migrate --noinput

# Create the first user, which our data import references:
django-admin createsuperuser --username admin --email admin@admin.local --noinput

# Import our data
python /var/www/whatsup/manage.py loaddata full_catalogue.json

./init
